import { InfoPage } from "../info-page";
export default function Page(){return <InfoPage eyebrow="ULTIMO AGGIORNAMENTO: 27 AGOSTO 2026" title="Privacy Policy" intro="Questa informativa descrive come MeetPuglia tratta i dati personali ai sensi del Regolamento (UE) 2016/679 (GDPR) e della normativa italiana applicabile." sections={[
 {title:"Titolare del trattamento",paragraphs:["Il Titolare è HOLD S.R.L., Via Salvatore Quasimodo 10, 70020 Bitritto (BA), Italia, C.F. e P. IVA 09207370728, REA BA-679395. Per richieste privacy: support@meetpuglia.it."]},
 {title:"Dati trattati",paragraphs:["Trattiamo dati di account e profilo; dati di eventi e prenotazioni; identificativi, importi e stato delle operazioni di pagamento; dati necessari agli organizzatori per Stripe Connect; immagini scelte dall’utente; notifiche e comunicazioni operative; dati tecnici, log e informazioni di sicurezza.","Con il permesso dell’utente, la posizione del dispositivo viene utilizzata per calcolare e ordinare gli eventi per distanza. La posizione corrente non viene salvata nel profilo. MeetPuglia non riceve né conserva il numero completo della carta, il CVC o le credenziali bancarie inserite su Stripe."]},
 {title:"Finalità e basi giuridiche",paragraphs:["I dati sono trattati per registrazione e autenticazione, gestione del profilo, pubblicazione e moderazione degli eventi, prenotazioni, pagamenti, rimborsi, assistenza e comunicazioni necessarie all’esecuzione del servizio.","Ulteriori basi sono gli obblighi di legge, il legittimo interesse alla sicurezza, prevenzione di frodi, continuità operativa e difesa di diritti, nonché il consenso o la scelta dell’utente per posizione, immagini e calendario quando richiesto."]},
 {title:"Fornitori e destinatari",paragraphs:["Possiamo avvalerci di Supabase per autenticazione, database, archiviazione e backend; Stripe per Checkout, pagamenti, prevenzione frodi, rimborsi e Connect; Resend e fornitori email per comunicazioni operative; Expo e fornitori dei sistemi operativi; Google e altri fornitori di geocodifica e localizzazione.","I dati possono essere comunicati a personale autorizzato, consulenti, autorità e soggetti coinvolti nella gestione di reclami o contestazioni nei casi previsti dalla legge. I dati personali non vengono venduti."]},
 {title:"Trasferimenti e conservazione",paragraphs:["Quando un fornitore tratta dati fuori dallo Spazio economico europeo, il trasferimento avviene mediante una decisione di adeguatezza o garanzie previste dal GDPR.","Account e profilo sono conservati finché l’account è attivo. Dati di pagamenti, rimborsi e operazioni possono essere conservati più a lungo per obblighi fiscali, contabili, antifrode, contestazioni e tutela di diritti. Log e backup seguono cicli tecnici limitati."]},
 {title:"Diritti dell’utente",paragraphs:["Nei casi previsti dal GDPR puoi chiedere accesso, rettifica, cancellazione, limitazione, portabilità e opposizione, nonché revocare il consenso. Scrivi a support@meetpuglia.it. Potremo chiedere informazioni necessarie a verificare l’identità.","Puoi inoltre proporre reclamo al Garante per la protezione dei dati personali o all’autorità di controllo competente."]},
 {title:"Minori, sicurezza e modifiche",paragraphs:["MeetPuglia non consente la creazione autonoma di un account a chi non ha compiuto 14 anni. Adottiamo misure tecniche e organizzative adeguate al rischio, pur non potendo garantire una sicurezza assoluta.","Questa informativa può essere aggiornata per modifiche normative, organizzative o del servizio. La versione vigente sarà resa disponibile sul sito e nell’app."]}
]}/>}
