import { InfoPage } from "../info-page";
export default function Page(){return <InfoPage eyebrow="ULTIMO AGGIORNAMENTO: 27 AGOSTO 2026" title="Termini e condizioni" intro="I presenti Termini regolano l’uso di MeetPuglia, servizio fornito da HOLD S.R.L. Creando un account o usando le funzioni riservate, l’utente accetta i Termini e dichiara di aver letto la Privacy Policy." sections={[
 {title:"Account e requisiti",paragraphs:["Per creare autonomamente un account occorre avere almeno 14 anni. L’utente deve fornire informazioni corrette, custodire le credenziali e segnalare accessi non autorizzati. Sono vietati impersonificazione, frodi, abusi, attività illegali o tentativi di aggirare la sicurezza."]},
 {title:"Ruolo della piattaforma",paragraphs:["MeetPuglia consente di scoprire, creare e gestire eventi gratuiti o a pagamento e prenotare un posto. Salvo diversa indicazione, gli eventi pubblicati dagli utenti sono organizzati e forniti dall’organizzatore indicato, non da HOLD S.R.L.","Per gli eventi a pagamento Stripe elabora la transazione e trasferisce la quota spettante all’organizzatore. La gestione del pagamento non rende HOLD S.R.L. organizzatore dell’evento."]},
 {title:"Obblighi degli organizzatori",paragraphs:["L’organizzatore garantisce correttezza di descrizione, immagini, categoria, luogo, date, durata, prezzo, capienza e requisiti. È responsabile dello svolgimento, della sicurezza, delle autorizzazioni, assicurazioni e degli obblighi fiscali e amministrativi.","Per ricevere pagamenti deve completare e mantenere valido l’onboarding Stripe Connect. Eventi e modifiche possono essere sottoposti a moderazione, rifiuto o rimozione."]},
 {title:"Prenotazioni e pagamenti",paragraphs:["Le prenotazioni gratuite non generano pagamenti. Per gli eventi a pagamento, il prezzo finale viene mostrato prima del Checkout e la prenotazione è confermata solo dopo la conferma sicura del pagamento.","Dal prezzo possono essere trattenuti i costi di servizio MeetPuglia e i costi di pagamento indicati. Un Checkout aperto o abbandonato non costituisce una prenotazione confermata."]},
 {title:"Cancellazioni e rimborsi",paragraphs:["Il partecipante può annullare fino a 72 ore prima dell’inizio ottenendo il rimborso previsto, al netto dei costi indicati prima dell’acquisto. Dopo tale termine può annullare e liberare il posto senza rimborso volontario, fatti salvi i diritti inderogabili.","Se l’organizzatore annulla un evento a pagamento, i rimborsi vengono gestiti secondo le condizioni applicabili; i costi di elaborazione Stripe non recuperabili possono restare esclusi. I tempi di accredito dipendono da Stripe e dal sistema bancario."]},
 {title:"Contenuti e comportamento",paragraphs:["È vietato pubblicare contenuti illegali, falsi, fraudolenti, pericolosi, discriminatori o lesivi di diritti altrui. L’utente conserva i diritti sui contenuti e concede a HOLD S.R.L. la licenza limitata necessaria per ospitarli, mostrarli e moderarli."]},
 {title:"Disponibilità e responsabilità",paragraphs:["Il servizio può essere modificato o sospeso per manutenzione, sicurezza o obblighi di legge. Nei limiti consentiti, HOLD S.R.L. non risponde della condotta degli utenti né della qualità, sicurezza o liceità degli eventi organizzati da terzi. Restano salve le responsabilità inderogabili e i diritti dei consumatori."]},
 {title:"Sospensione, eliminazione e contatti",paragraphs:["Un account può essere limitato o sospeso per violazioni, frodi, rischi di sicurezza o obblighi di legge. L’eliminazione può essere differita se esistono eventi attivi, pagamenti, rimborsi o obblighi pendenti.","Si applica la legge italiana, ferme le norme inderogabili e il foro del consumatore quando previsto. Per assistenza o reclami: support@meetpuglia.it."]}
]}/>}
